# -*- coding: utf-8 -*-
"""Copy of till recommended sys

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBhgxhskpqSopT9ajuWF1-YhK9bmEDHx
"""

import pandas as pd
import numpy as np

df = pd.read_csv("Indian_Kids_Screen_Time.csv")
print(df.shape)
df.head()

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.columns

df = df.drop_duplicates()

print(df.isnull().sum())

for col in df.columns:
    if df[col].dtype == 'object':
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna(df[col].mean(), inplace=True)

df = df.replace(r'^\s*$', np.nan, regex=True)
df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

df = df.convert_dtypes()
df.dtypes

# df = pd.read_csv("/content/Indian_Kids_Screen_Time.csv")
df['health_impacts'] = df['health_impacts'].fillna("None")
display(df.isnull().sum())

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.bar(df['age'], df['avg_daily_screen_time_hr'], color='skyblue')
plt.xlabel("Age")
plt.ylabel("Average Screen Time (hours)")
plt.title("Average Screen Time by Age")
plt.show()

plt.figure(figsize=(6,5))
gender_categories = df['gender'].unique()
plt.boxplot([df[df['gender']==cat]['avg_daily_screen_time_hr'] for cat in gender_categories],
             tick_labels=gender_categories)
plt.title("Screen Time Distribution by Gender")
plt.ylabel("Screen Time (hours)")
plt.show()

plt.figure(figsize=(7,5))
plt.scatter(df['age'], df['avg_daily_screen_time_hr'], color='green')
plt.title("Relation between Age and Screen Time")
plt.xlabel("Age")
plt.ylabel("Screen Time (hours)")
plt.show()

num_cols = df.select_dtypes(include=np.number).columns.tolist()

for col in num_cols:
    plt.figure(figsize=(6,4))
    plt.hist(df[col], bins=15, color='skyblue', edgecolor='black')
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Count')
    plt.show()

cat_cols = df.select_dtypes(include='object').columns.tolist()

for col in cat_cols:
    plt.figure(figsize=(6,4))
    df[col].value_counts().plot(kind='bar', color='lightcoral')
    plt.title(f'Category Count - {col}')
    plt.xlabel(col)
    plt.ylabel('Count')
    plt.show()

plt.hist(df['age'], bins=10, color='skyblue', edgecolor='black')
plt.title('Univariate Analysis - Age Distribution')
plt.xlabel('Age')
plt.ylabel('Count')
plt.show()

plt.scatter(df['age'], df['avg_daily_screen_time_hr'], color='mediumseagreen')
plt.title('Bivariate Analysis - Age vs Screen Time')
plt.xlabel('Age')
plt.ylabel('Screen Time (hours)')
plt.show()

import seaborn as sns

sns.boxplot(x='health_impacts', y='avg_daily_screen_time_hr', data=df, palette='Set2')
plt.title('Bivariate Analysis - Screen Time vs Health Impact')
plt.xlabel('Health Impact')
plt.ylabel('Screen Time (hours)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation between Numeric Variables")
plt.show()

from itertools import combinations

num_pairs = list(combinations(num_cols, 2))

for (x, y) in num_pairs:
    plt.figure(figsize=(6,4))
    plt.scatter(df[x], df[y], color='mediumseagreen', alpha=0.6)
    plt.title(f'{x} vs {y}')
    plt.xlabel(x)
    plt.ylabel(y)
    plt.show()

def screen_limit(Age):
    if Age < 2:
        return 0
    elif Age <= 5:
        return 1
    elif Age <= 12:
        return 2
    else:
        return 3

df['limit'] = df['age'].apply(screen_limit)
df['exceeds'] = df['exceeded_recommended_limit'] > df['limit']

df['exceeded_recommended_limit'].value_counts()

counts = df['exceeds'].value_counts().sort_index()
labels = ['Within Limit', 'Exceeds']
percentages = (counts / counts.sum() * 100).round(1)

gender_avg = df.groupby('gender')['avg_daily_screen_time_hr'].mean()
print(gender_avg)

df[df['exceeded_recommended_limit'] == False].sort_values('avg_daily_screen_time_hr', ascending=False)

avg = df['avg_daily_screen_time_hr'].mean()
print(avg)

avg_screen = df['avg_daily_screen_time_hr'].mean()
print("Average Screen Time:", round(avg_screen, 2), "hrs/day")

age = int(input("Enter your age: "))
gender = input("Enter your gender (M/F): ").upper()
time = float(input("Enter your avg daily screen time (hrs): "))

if time > avg_screen:
    print(" Above average! Try to reduce screen time.")
elif time < avg_screen:
    print("Below average! Keep it up.")
else:
    print("You are at the average screen time level.")

# Group by age and calculate mean screen time
thresholds = df.groupby('age')['avg_daily_screen_time_hr'].mean().round(2)
print(thresholds)

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

class ScreenTimeRecommendationSystem:

    def __init__(self, csv_path='Indian_Kids_Screen_Time.csv'):
        print("="*70)
        print("INITIALIZING SCREEN TIME RECOMMENDATION SYSTEM")
        print("="*70)

        # Load dataset
        print("\n📂 Loading dataset...")
        self.data = pd.read_csv(csv_path)
        print(f"✓ Loaded {len(self.data)} records")

        # Data cleaning
        print("\n🧹 Cleaning data...")
        original_size = len(self.data)
        self.data = self.data.drop_duplicates()
        print(f"✓ Removed {original_size - len(self.data)} duplicates")

        # Create age groups
        self.data['Age_Group'] = self.data['Age'].apply(self._get_age_group)

        # Calculate baseline statistics
        print("\n📊 Calculating baseline statistics...")
        self.overall_avg = self.data['Avg_Daily_Screen_Time_hr'].mean()
        self.gender_stats = self.data.groupby('Gender')['Avg_Daily_Screen_Time_hr'].mean().to_dict()
        self.device_stats = self.data.groupby('Primary_Device')['Avg_Daily_Screen_Time_hr'].mean().to_dict()
        self.age_group_stats = self.data.groupby('Age_Group')['Avg_Daily_Screen_Time_hr'].mean().to_dict()
        self.location_stats = self.data.groupby('Urban_or_Rural')['Avg_Daily_Screen_Time_hr'].mean().to_dict()

        print(f"✓ Overall Average: {self.overall_avg:.2f} hours/day")
        print("\n✅ System ready!")
        print("="*70)

    def get_recommended_limit(self, age):
        if age <= 10:
            return 2.0  # 8-10 years: 2 hours
        elif age <= 14:
            return 2.5  # 11-14 years: 2.5 hours
        else:
            return 3.0  # 15-18 years: 3 hours

    def _get_age_group(self, age):
        if age <= 10:
            return '8-10 years'
        elif age <= 14:
            return '11-14 years'
        else:
            return '15-18 years'

    def _classify_severity(self, exceeds_by, limit):
        if exceeds_by <= 0:
            return 'Healthy'
        elif exceeds_by <= limit * 0.5:
            return 'Moderate'
        elif exceeds_by <= limit:
            return 'High'
        else:
            return 'Critical'

    def analyze_user_input(self, age, gender, device, location, screen_time):

        age_group = self._get_age_group(age)
        recommended_limit = self.get_recommended_limit(age)

        # Get peer group averages
        gender_avg = self.gender_stats.get(gender, self.overall_avg)
        device_avg = self.device_stats.get(device, self.overall_avg)
        age_avg = self.age_group_stats.get(age_group, self.overall_avg)
        location_avg = self.location_stats.get(location, self.overall_avg)

        # Calculate differences
        comparisons = {
            'Overall Average': (self.overall_avg, screen_time - self.overall_avg),
            f'Gender ({gender})': (gender_avg, screen_time - gender_avg),
            f'Device ({device})': (device_avg, screen_time - device_avg),
            f'Age Group ({age_group})': (age_avg, screen_time - age_avg),
            f'Location ({location})': (location_avg, screen_time - location_avg)
        }

        # Determine severity
        exceeds_by = screen_time - recommended_limit
        severity = self._classify_severity(exceeds_by, recommended_limit)

        return {
            'age': age,
            'age_group': age_group,
            'gender': gender,
            'device': device,
            'location': location,
            'screen_time': screen_time,
            'recommended_limit': recommended_limit,
            'exceeds_by': exceeds_by,
            'severity': severity,
            'comparisons': comparisons
        }

    def generate_recommendations(self, analysis):
        recommendations = []
        severity = analysis['severity']
        exceeds_by = analysis['exceeds_by']
        age = analysis['age']
        device = analysis['device']

        # Health-based recommendations
        if severity == 'Healthy':
            recommendations.append(" Good")
            recommendations.append("Continue lifestyle.")
        elif severity == 'Moderate':
            recommendations.append(f"Your screen time exceeds recommendations by {exceeds_by:.1f} hours/day.")
            recommendations.append("Try to reduce screentime by 15-30 minutes per week.")
        elif severity == 'High':
            recommendations.append(f"WARNING: Screen time significantly exceeds recommendations by {exceeds_by:.1f} hours/day.")
            recommendations.append("Immediate action needed: Reduce screen time by at least 1 hour daily.")
        else:  # Critical
            recommendations.append(f"CRITICAL: Screen time is {exceeds_by:.1f} hours ABOVE recommendations!")
            recommendations.append("URGENT: Reduce screen time by 2-3 hours immediately and seek professional guidance.")

        # Device-specific recommendations
        device_tips = {
            'Smartphone': [
                "Enable screen time limits using built-in features",
                "Move distracting apps to folders or remove from home screen",
                "Use grayscale mode to reduce appeal"
            ],
            'Laptop': [
                "Use website blockers during study/work hours",
                "Practice the 20-20-20 rule: Every 20 mins, look 20 feet away for 20 seconds",
                "Set specific time blocks for laptop use"
            ],
            'TV': [
                "Avoid binge-watching; set episode limits",
            ],
            'Tablet': [
                "Use parental controls to limit usage time",
                "Keep tablets in common areas, not bedrooms"
            ]
        }

        recommendations.extend(device_tips.get(device, []))

        # Age-specific recommendations
        if age <= 10:
            recommendations.extend([
                "Prioritize outdoor play and physical activities",
                "Encourage creative activities like drawing and building",
                "Co-view content with parents when possible"
            ])
        elif age <= 14:
            recommendations.extend([
                "Balance screen time with hobbies and sports",
                "Set homework completion before recreational screen time",
                "Discuss online safety and digital citizenship"
            ])
        else:
            recommendations.extend([
                "Practice self-regulation and time management",
                "Use productivity apps to track and limit usage",
                "Engage in social activities without screens"
            ])

        # General health recommendations
        recommendations.extend([
            "HEALTH TIPS:",
            "• Follow the 20-20-20 rule to prevent eye strain",
            "• Maintain proper posture while using devices",
            "• Avoid screens 1 hour before bedtime",
            "• Stay physically active for at least 60 minutes daily",
            "• Ensure adequate sleep (8-10 hours for children)"
        ])

        return recommendations
    def get_statistics(self):
        stats = {
            'Total Records': len(self.data),
            'Overall Average': f"{self.overall_avg:.2f} hours/day",
            'By Gender': self.gender_stats,
            'By Device': self.device_stats,
            'By Age Group': self.age_group_stats,
            'By Location': self.location_stats
        }
        return stats
    def display_analysis(self, analysis, recommendations):
        print("="*70)
        print("PERSONALIZED SCREEN TIME ANALYSIS REPORT")
        print("="*70)

        print(f" User Profile:")
        print(f"   Age: {analysis['age']} years ({analysis['age_group']})")
        print(f"   Gender: {analysis['gender']}")
        print(f"   Primary Device: {analysis['device']}")
        print(f"   Location: {analysis['location']}\n")

        print(f"📱 Screen Time Analysis:")
        print(f"   Current Usage: {analysis['screen_time']:.2f} hours/day")
        print(f"   Recommended Limit: {analysis['recommended_limit']:.2f} hours/day\n")

        if analysis['exceeds_by'] > 0:
            print(f"Exceeds by: {analysis['exceeds_by']:.2f} hours/day")
        else:
            print(f"Within limit by: {abs(analysis['exceeds_by']):.2f} hours/day")

        print(f"   Severity Level: {analysis['severity']}")

        print(f"📈 Peer Group Comparisons:")
        for category, (avg, diff) in analysis['comparisons'].items():
            symbol = "↑" if diff > 0 else "↓"
            print(f"   {category}: {avg:.2f}h (You: {symbol} {abs(diff):.2f}h)\n")

        print(f"💡 PERSONALIZED RECOMMENDATIONS:")
        for rec in recommendations:
            print(f"   {rec}")
        print("\n")
        print("="*70)

def get_user_input():
    print("\n" + "="*70)
    print("🎯 SCREEN TIME RECOMMENDATION SYSTEM - USER INPUT")
    print("="*70)

    # Get Age
    while True:
        try:
            age = int(input("\n📅 Enter age (8-18): "))
            if 8 <= age <= 18:
                break
            else:
                print("❌ Age must be between 8 and 18")
        except ValueError:
            print("❌ Please enter a valid number")

    # Get Gender
    while True:
        gender = input("\n👤 Enter gender (Male/Female): ").strip().lower()
        if gender in ['male', 'm']:
            gender = 'Male'
            break
        elif gender in ['female', 'f']:
            gender = 'Female'
            break
        else:
            print("❌ Please enter 'Male' or 'Female'")


    # Get Device
    devices = ['Smartphone', 'Laptop', 'TV', 'Tablet']
    print("\n📱 Select primary device:")
    for i, device in enumerate(devices, 1):
        print(f"   {i}. {device}")

    while True:
        try:
            device_choice = int(input("Enter choice (1-4): "))
            if 1 <= device_choice <= 4:
                device = devices[device_choice - 1]
                break
            else:
                print("❌ Please enter a number between 1 and 4")
        except ValueError:
            print("❌ Please enter a valid number")

    # Get Location
    while True:
        location = input("\n🏙️ Enter location (Urban/Rural): ").strip().lower()
        if location in ['urban', 'u']:
            location = 'Urban'
            break
        elif location in ['rural', 'r']:
            location = 'Rural'
            break
        else:
            print("❌ Please enter 'Urban' or 'Rural'")


    # Get Educational Screen Time
    while True:
        try:
            educational_hours = float(input("\n📚 Enter educational screen time (hours/day): "))
            if 0 <= educational_hours <= 24:
                break
            else:
                print("❌ Educational hours must be between 0 and 24")
        except ValueError:
            print("❌ Please enter a valid number")

    # Get Recreational Screen Time
    while True:
        try:
            recreational_hours = float(input("\n🎮 Enter recreational screen time (hours/day): "))
            if 0 <= recreational_hours <= 24:
                break
            else:
                print("❌ Recreational hours must be between 0 and 24")
        except ValueError:
            print("❌ Please enter a valid number")

    # Calculate total screen time and ratio
    screen_time = educational_hours + recreational_hours

    # Calculate Educational to Recreational Ratio
    if recreational_hours > 0:
        edu_rec_ratio = educational_hours / recreational_hours
    else:
        edu_rec_ratio = educational_hours  # If no recreational time, ratio = educational hours

    print(f"\n📊 Total Screen Time: {screen_time:.2f} hours/day")
    print(f"📊 Educational to Recreational Ratio: {edu_rec_ratio:.2f}")

    # Get Health Impacts
    print("\n🏥 Select Health Impacts (separate multiple with commas):")
    print("   Options: Poor Sleep, Eye Strain, Anxiety, Behavioral Issues, None")
    print("   Example: Poor Sleep, Eye Strain")

    while True:
        health_input = input("\nEnter health impacts: ").strip()
        impacts = [impact.strip().title() for impact in health_input.split(',')]
        if health_input:
            # Split by comma and clean up
            health_impacts = [impact.strip() for impact in health_input.split(',')]
            # Validate each impact
            valid_impacts = ['Poor Sleep', 'Eye Strain', 'Anxiety', 'Behavioral Issues', 'None']

            invalid = [h for h in health_impacts if h not in valid_impacts]
            if invalid:
                print(f"❌ Invalid health impacts: {', '.join(invalid)}")
                print(f"   Please use only: {', '.join(valid_impacts)}")
            else:
                break
        else:
            health_impacts = ['None']
            break

    return {
        'age': age,
        'gender': gender,
        'device': device,
        'location': location,
        'screen_time': screen_time,
        'educational_hours': educational_hours,
        'recreational_hours': recreational_hours,
        'edu_rec_ratio': edu_rec_ratio,
        'health_impacts': health_impacts
    }


def analyze_case(rec_system):
    # Get user input
    user_data = get_user_input()

    # Analyze
    analysis = rec_system.analyze_user_input(
        age=user_data['age'],
        gender=user_data['gender'],
        device=user_data['device'],
        location=user_data['location'],
        screen_time=user_data['screen_time']
    )

    # Add the extra fields to analysis
    analysis['educational_hours'] = user_data['educational_hours']
    analysis['recreational_hours'] = user_data['recreational_hours']
    analysis['edu_rec_ratio'] = user_data['edu_rec_ratio']
    analysis['health_impacts'] = user_data['health_impacts']

    # Generate recommendations
    recommendations = rec_system.generate_recommendations(analysis)

    # Display results
    rec_system.display_analysis(analysis, recommendations)

    return analysis, recommendations

def run_multiple_analyses(rec_system, num_cases=1):
    results = []

    for i in range(num_cases):
        print(f"\n\n{'='*70}")
        print(f"CASE {i+1} of {num_cases}")
        print('='*70)

        analysis, recommendations = analyze_case(rec_system)
        results.append({
            'analysis': analysis,
            'recommendations': recommendations
        })

        if i < num_cases - 1:
            continue_choice = input("\n\nContinue to next case? (yes/no): ").strip().lower()
            if continue_choice not in ['yes', 'y']:
                break

    print(f"\n\n✅ Completed {len(results)} analysis/analyses")
    return results


# Quick analysis function for manual input
def quick_analyze(rec_system, age, gender, device, location, educational_hours, recreational_hours, health_impacts):
    # Calculate total screen time and ratio
    screen_time = educational_hours + recreational_hours

    if recreational_hours > 0:
        edu_rec_ratio = educational_hours / recreational_hours
    else:
        edu_rec_ratio = educational_hours

    # Display the breakdown
    print(f"\n📊 Screen Time Breakdown:")
    print(f"   Educational: {educational_hours:.2f} hours/day")
    print(f"   Recreational: {recreational_hours:.2f} hours/day")
    print(f"   Total: {screen_time:.2f} hours/day")
    print(f"   Edu/Rec Ratio: {edu_rec_ratio:.2f}")
    print(f"   Health Impacts: {', '.join(health_impacts)}")

    # Analyze
    analysis = rec_system.analyze_user_input(age, gender, device, location, screen_time)

    # Add the extra data to analysis
    analysis['educational_hours'] = educational_hours
    analysis['recreational_hours'] = recreational_hours
    analysis['edu_rec_ratio'] = edu_rec_ratio
    analysis['health_impacts'] = health_impacts

    # Generate recommendations
    recommendations = rec_system.generate_recommendations(analysis)

    # Display results
    rec_system.display_analysis(analysis, recommendations)

    return analysis, recommendations

counts = df['exceeded_recommended_limit'].value_counts()
percentages = df['exceeded_recommended_limit'].value_counts(normalize=True) * 100

# Filter the DataFrame to include only rows where 'exceeded_recommended_limit' is True
exceeded_df = df[df['exceeded_recommended_limit'] == True]

# Calculate the average screen time for those who exceeded the limit
avg_screen_exceeded = exceeded_df['avg_daily_screen_time_hr'].mean()

print("Count of individuals who exceeded the recommended screen time limit:")
print(counts)
print("\nPercentage of individuals who exceeded the recommended screen time limit:")
print(percentages)
print(f"\nAverage screen time for those who exceeded the limit: {avg_screen_exceeded:.2f} hours")

# from user_input import analyze_case # This import is not needed
rec_system = ScreenTimeRecommendationSystem()
new_analysis, new_recs = analyze_case(rec_system)
# plot_peer_comparison(new_analysis) # These functions are not defined in the notebook
# create_dashboard(new_analysis, rec_system.data) # These functions are not defined in the notebook

print("\n SUCCESSFUL REPORT")

df.to_csv("Cleaned_Indian_Kids_Screen_Time.csv", index=False)
print("Cleaned file saved successfully!")



"""**Note:** Please ensure all preceding cells that define and modify the `df` DataFrame are executed before running the cell below to avoid `NameError`."""
